# keybinds:
- key: a
  style: fill
- key: d # Solid line
  style: stroke;stroke-dasharray:none;-inkscape-stroke:none
- key: s # Stroked line
  style: stroke;stroke-dasharray:22.67720315,3.77952756;stroke-opacity:1;
- key: v # Paint white
  style: :#ffffff
- key: b # Paint black
  style: :#000000
- key: c # Removes fill, for example.
  style: :none
- key: g # Add an arrow header. #ConcaveTriangle is hardcoded in the styler.
  style: marker-end:url(#ConcaveTriangle);

# Rebinds
- key: w
  rebind_to: e
- key: e
  rebind_to: w
